trigger:
  - main

pool:
  vmImage: ubuntu-latest

resources:
  repositories:
  - repository: terraform
    type: git
    name: scripts/Terraform
steps:
  - checkout: self
    submodules: true 
  - checkout: terraform
    submodules: true

  - task: TerraformInstaller@0
    inputs:
     terraformVersion: '1.3.4'

  - task: TerraformTaskV2@2
    inputs:
     provider: 'azurerm'
     command: 'init'
     workingDirectory: '/home/vsts/work/1/s/Terraform/sites/thepaynetrain.com/www/azure'
     backendServiceArm: 'Production Service(3f6d29b1-08f7-4d8b-a298-8ea97dd77eda)'
     backendAzureRmResourceGroupName: 'thepaynetrain-com-rg'
     backendAzureRmStorageAccountName: 'thepaynetrainsa'
     backendAzureRmContainerName: 'terraform'
     backendAzureRmKey: 'www-thepaynetrain-com.prod.terraform.tfstate'
  
  - task: TerraformTaskV2@2
    inputs:
      provider: 'azurerm'
      command: 'apply'
      workingDirectory: '/home/vsts/work/1/s/Terraform/sites/thepaynetrain.com/www/azure'
      environmentServiceNameAzureRM: 'Production Service(3f6d29b1-08f7-4d8b-a298-8ea97dd77eda)'
  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      api_location: 'api'
      output_location: ''
      workingDirectory: '/home/vsts/work/1/s/www.thepaynetrain.com/'
      azure_static_web_apps_api_token: $(www-thepaynetrain-com-ds)

  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Production Service(3f6d29b1-08f7-4d8b-a298-8ea97dd77eda)'
      KeyVaultName: 'thepaynetrain-com-kv'
      SecretsFilter: '*'
      RunAsPreJob: true
  - task: Docker@2
    inputs:
      containerRegistry: 'dockerhub'
      repository: 'lapayne82/homepage'
      command: 'buildAndPush'
      Dockerfile: '**/homepage.Dockerfile'
      tags: |
        $(Build.BuildId)
        latest

  - task: Docker@2
    inputs:
      containerRegistry: 'GCP docker www.thepaynetrain.com'
      command: 'login'

  - task: Docker@2
    inputs:
      containerRegistry: 'GCP docker www.thepaynetrain.com'
      repository: 'www-thepaynetrain-com/www-thepaynetrain-com/hompage'
      command: 'buildAndPush'
      Dockerfile: '**/homepage.Dockerfile'
      tags: |
        latest
        $(Build.BuildId)