trigger:
  - main

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self
    submodules: true

  - task: TerraformInstaller@0
    inputs:
     terraformVersion: '1.0.5'

  - task: AzureStaticWebApp@0
    inputs:
      app_location: '/'
      api_location: 'api'
      output_location: ''
      azure_static_web_apps_api_token: $(www-thepaynetrain-com-ds)

  - task: AzureKeyVault@2
    inputs:
      azureSubscription: 'Production Service(3f6d29b1-08f7-4d8b-a298-8ea97dd77eda)'
      KeyVaultName: 'thepaynetrain-com-kv'
      SecretsFilter: '*'
      RunAsPreJob: true